name: build

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '**.json'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '**.json'

env:
  WITH_SBX: "OFF"

jobs:
  build_win32:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Clone SBX extension
      if: env.WITH_SBX == 'ON'
      uses: actions/checkout@v4
      with:
        repository: spelltide-games/sbx_extension
        ssh-key: ${{ secrets.WITH_SBX_KEY }}
        path: sbx_extension
        fetch-depth: 0
        submodules: recursive
        persist-credentials: false
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.26.x'
    - name: Compile
      shell: bash
      run: |
        python -m stubgen ${{ env.WITH_SBX == 'ON' && '--with-sbx' || '' }}
        python build.py --config Release --platform win32 ${{ env.WITH_SBX == 'ON' && '--with-sbx' || '' }}
    - uses: actions/upload-artifact@v4
      with:
        name: windows
        path: demo/addons/godot-pocketpy/bin/windows
  build_macos:
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Clone SBX extension
        if: env.WITH_SBX == 'ON'
        uses: actions/checkout@v4
        with:
          repository: spelltide-games/sbx_extension
          ssh-key: ${{ secrets.WITH_SBX_KEY }}
          path: sbx_extension
          fetch-depth: 0
          submodules: recursive
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.26.x'
      - name: Compile
        run: |
          python -m stubgen ${{ env.WITH_SBX == 'ON' && '--with-sbx' || '' }}
          python build.py --config Release --platform macos ${{ env.WITH_SBX == 'ON' && '--with-sbx' || '' }}
      - uses: actions/upload-artifact@v4
        with:
          name: macos
          path: demo/addons/godot-pocketpy/bin/macos
  build_android:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Clone SBX extension
        if: env.WITH_SBX == 'ON'
        uses: actions/checkout@v4
        with:
          repository: spelltide-games/sbx_extension
          ssh-key: ${{ secrets.WITH_SBX_KEY }}
          path: sbx_extension
          fetch-depth: 0
          submodules: recursive
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.26.x'
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r23
          local-cache: false
          add-to-path: false
      - name: Compile
        run: |
          python -m stubgen ${{ env.WITH_SBX == 'ON' && '--with-sbx' || '' }}
          python build.py --config Release --platform android ${{ env.WITH_SBX == 'ON' && '--with-sbx' || '' }}
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - uses: actions/upload-artifact@v4
        with:
          name: android
          path: demo/addons/godot-pocketpy/bin/android
  build_ios:
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Clone SBX extension
        if: env.WITH_SBX == 'ON'
        uses: actions/checkout@v4
        with:
          repository: spelltide-games/sbx_extension
          ssh-key: ${{ secrets.WITH_SBX_KEY }}
          path: sbx_extension
          fetch-depth: 0
          submodules: recursive
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.26.x'
      - name: Compile
        run: |
          python -m stubgen ${{ env.WITH_SBX == 'ON' && '--with-sbx' || '' }}
          python build.py --config Release --platform ios ${{ env.WITH_SBX == 'ON' && '--with-sbx' || '' }}
      - uses: actions/upload-artifact@v4
        with:
          name: ios
          path: demo/addons/godot-pocketpy/bin/ios
  merge:
      runs-on: ubuntu-latest
      needs: [ build_win32, build_macos, build_android, build_ios ]
      steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Clone SBX extension
        if: env.WITH_SBX == 'ON'
        uses: actions/checkout@v4
        with:
          repository: spelltide-games/sbx_extension
          ssh-key: ${{ secrets.WITH_SBX_KEY }}
          path: sbx_extension
          fetch-depth: 0
          submodules: recursive
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: "Run stubgen"
        run: |
          python -m stubgen ${{ env.WITH_SBX == 'ON' && '--with-sbx' || '' }}
          mkdir -p demo/addons/godot-pocketpy/bin
          # remove .gitignore
          rm -f .gitignore
        
      - name: "Merge win32"
        uses: actions/download-artifact@v4.1.7
        with:
          name: windows
          path: demo/addons/godot-pocketpy/bin/windows

      - name: "Merge macos"
        uses: actions/download-artifact@v4.1.7
        with:
          name: macos
          path: demo/addons/godot-pocketpy/bin/macos

      - name: "Merge android"
        uses: actions/download-artifact@v4.1.7
        with:
          name: android
          path: demo/addons/godot-pocketpy/bin/android
          
      - name: "Merge ios"
        uses: actions/download-artifact@v4.1.7
        with:
          name: ios
          path: demo/addons/godot-pocketpy/bin/ios

      - name: "Use release libraries"
        run: |
          sed -i 's/template_debug/template_release/g' demo/addons/godot-pocketpy/godot-pocketpy.gdextension

      - name: "Upload merged artifact"
        uses: actions/upload-artifact@v4.3.3
        with:
          name: godot-pocketpy
          path: demo/addons/godot-pocketpy
